services:
  - type: web
    name: energyclick
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: BOT_TOKEN
        value: ""
      - key: OWNER_ID
        value: ""
      - key: WEBAPP_URL
        value: ""
